name: Deploy Docs

on:
  push:
    paths:
      - 'docs/**'
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      COMMIT: ${{ github.sha }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Set up PNPM
        uses: pnpm/action-setup@v2
        with:
          run_install: false
      - name: Fetch PNPM Store
        id: pnpm-cache
        run: echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      - name: Restore PNPM Cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build --filter=@lamware/docs
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./docs/content/.vitepress/dist
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: docs
          cname: docs.evil.kiwi
