name: Deploy Docs

on:
  push:
    paths:
      - 'docs/**'
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Build Static
        run: yarn docs build
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./docs/content/.vuepress/dist
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: docs
          cname: docs.evil.kiwi
